const key='chaenggim-v1';
const uid=()=>crypto.randomUUID();
const makeup=['립스틱','파운데이션','콤팩트','아이라이너','아이섀도우'];
const make=(names,group)=>names.map(name=>({id:uid(),name,group,checked:false}));
const initial=()=>({selected:'bon',places:[{id:'bon',name:'본원',items:[...make(['회원 명찰','가방'],'기본'),...make(['치약·칫솔 세트','비누','헤어 로션','샴푸','바디 샴푸','목욕 타월','마른 수건'],'세면도구'),...make(['속옷','팬티','양말'],'의류'),...make(makeup,'화장품')]},{id:'gym',name:'운동',items:[]},{id:'acting',name:'학원',items:[...make(['필기 노트','교재','가까이 보는 안경','멀리 보는 안경','가방'],'준비물'),...make(makeup,'화장품')]},{id:'retreat',name:'지역 수련회',items:[]},{id:'hiking',name:'등산',items:[...make(['등산화','모자','장갑','고어텍스 아우터','바지','스틱','여벌 옷'],'의류·장비'),...make(['물 3개','캔커피','점심 먹거리','초콜릿','진저샷'],'먹거리')]},{id:'other',name:'기타 외출',items:[]}],common:make(['핸드폰','카드'],'공통 필수품'),checks:{},locations:[{id:uid(),name:'카드·카드지갑',location:'현관 바로 앞 신발장 위',checked:false},{id:uid(),name:'핸드폰',location:'침대 머리맡',checked:false},{id:uid(),name:'안경',location:'침대 선반',checked:false}]});
let data;try{data=JSON.parse(localStorage.getItem(key));if(!data?.places?.length) data=initial()}catch{data=initial()}let mode='out',editing=null;const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const place=()=>data.places.find(p=>p.id===data.selected)||data.places[0];
function save(){try{localStorage.setItem(key,JSON.stringify(data));$('saved').textContent='이 브라우저에 저장됨'}catch{$('saved').textContent='저장 공간 부족 · 저장하지 못했어요'}}
function checked(item){return mode==='home'?item.checked:item.group==='공통 필수품'?!!data.checks[place().id+item.id]:item.checked}
function render(){const p=place();$('title').textContent=mode==='out'?p.name+' 가는 날':'다녀왔어요';$('places').innerHTML=data.places.map(x=>`<button data-place="${x.id}" class="${p.id===x.id?'active':''}" aria-pressed="${p.id===x.id}">${esc(x.name)}<span class="place-count">${x.items.length+data.common.length}</span></button>`).join('');$('outTab').classList.toggle('active',mode==='out');$('homeTab').classList.toggle('active',mode==='home');$('outTab').setAttribute('aria-pressed',mode==='out');$('homeTab').setAttribute('aria-pressed',mode==='home');$('editPlace').hidden=mode==='home';$('addForm').hidden=mode==='home';$('listTitle').textContent=mode==='out'?'준비물':'제자리에 놓았나요?';$('reset').textContent=mode==='out'?'↻ 새 외출 시작':'↻ 정리 체크 초기화';const items=mode==='out'?[...data.common,...p.items]:data.locations;const done=items.filter(checked).length;$('progressLabel').textContent=mode==='out'?'오늘의 준비':'오늘의 정리';$('progressText').textContent=`${done} / ${items.length}`;$('progress').max=items.length||1;$('progress').value=done;$('encouragement').textContent=items.length&&done===items.length?(mode==='out'?'모두 챙겼어요. 잘 다녀오세요!':'모두 제자리에 두었어요. 편히 쉬세요!'):`${items.length-done}개만 더 확인해 주세요.`;let prev='';$('items').innerHTML=items.map(x=>{const group=mode==='out'?x.group:'';const head=group!==prev?`<p class="group-label">${esc(group)}</p>`:'';prev=group;return head+`<div class="item ${checked(x)?'done':''}"><label><input type="checkbox" data-check="${x.id}" ${checked(x)?'checked':''}><span><span class="name">${esc(x.name)}</span>${mode==='home'?`<small>${esc(x.location)}</small>`:''}</span></label><button data-edit="${x.id}" aria-label="${esc(x.name)} 수정">수정</button></div>`}).join('')||'<p class="empty">물건과 위치를 추가해 주세요.</p>';$('locations').innerHTML=data.locations.map(x=>`<div class="location"><div><strong>${esc(x.name)}</strong><button data-location="${x.id}" aria-label="${esc(x.name)} 위치 수정">수정</button></div><p>${esc(x.location||'위치를 입력해 주세요')}</p></div>`).join('')}
function openEditor(type,item){editing={type,item};const loc=type==='location';$('dialogTitle').textContent=type==='place'?'장소 설정':loc?'물건과 고정 위치':'준비물 수정';$('editName').value=item?.name||'';$('editLocation').value=item?.location||'';$('locationLabel').hidden=!loc;$('editLocation').hidden=!loc;$('delete').hidden=!item||(type==='place'&&data.places.length===1);$('editor').showModal();$('editName').focus()}
$('places').onclick=e=>{const b=e.target.closest('[data-place]');if(b){data.selected=b.dataset.place;save();render()}};
$('outTab').onclick=()=>{mode='out';render()};$('homeTab').onclick=()=>{mode='home';render()};$('addPlace').onclick=()=>openEditor('place');$('editPlace').onclick=()=>openEditor('place',place());$('addLocation').onclick=()=>openEditor('location');$('locations').onclick=e=>{const b=e.target.closest('[data-location]');if(b)openEditor('location',data.locations.find(x=>x.id===b.dataset.location))};
$('addForm').onsubmit=e=>{e.preventDefault();const value=$('newItem').value.trim();if(!value)return;place().items.push(...make([value],'직접 추가한 준비물'));$('newItem').value='';save();render();$('newItem').focus()};
$('items').onchange=e=>{const id=e.target.dataset.check;if(!id)return;const x=(mode==='home'?data.locations:[...data.common,...place().items]).find(x=>x.id===id);if(mode==='out'&&x.group==='공통 필수품')data.checks[place().id+x.id]=e.target.checked;else x.checked=e.target.checked;save();render()};
$('items').onclick=e=>{const b=e.target.closest('[data-edit]');if(b){const x=(mode==='home'?data.locations:[...data.common,...place().items]).find(x=>x.id===b.dataset.edit);openEditor(mode==='home'?'location':'item',x)}};
$('reset').onclick=()=>{if(!confirm(mode==='out'?'목록은 유지하고 이 장소의 체크 표시를 모두 지울까요?':'제자리 체크 표시를 모두 지울까요?'))return;if(mode==='home')data.locations.forEach(x=>x.checked=false);else{place().items.forEach(x=>x.checked=false);data.common.forEach(x=>delete data.checks[place().id+x.id])}save();render()};
$('cancel').onclick=()=>$('editor').close();$('editForm').onsubmit=e=>{e.preventDefault();const name=$('editName').value.trim();if(!name)return;const {type,item}=editing;if(item){item.name=name;if(type==='location')item.location=$('editLocation').value.trim()}else if(type==='place'){const p={id:uid(),name,items:[]};data.places.push(p);data.selected=p.id;mode='out'}else data.locations.push({id:uid(),name,location:$('editLocation').value.trim(),checked:false});save();render();$('editor').close()};
$('delete').onclick=()=>{const {type,item}=editing;if(!confirm(`‘${item.name}’${data.common.includes(item)?' 공통 필수품을 모든 장소에서':'을'} 삭제할까요?`))return;if(type==='place'){data.places=data.places.filter(x=>x.id!==item.id);data.selected=data.places[0].id}else if(type==='location')data.locations=data.locations.filter(x=>x.id!==item.id);else{data.common=data.common.filter(x=>x.id!==item.id);place().items=place().items.filter(x=>x.id!==item.id)}save();render();$('editor').close()};render();
