document.body.insertAdjacentHTML('beforeend','<dialog id="renameCategoryDialog"><form id="renameCategoryForm"><h2 id="renameCategoryTitle">준비물 카테고리 수정</h2><label for="renameCategoryInput">카테고리 이름</label><input id="renameCategoryInput" required maxlength="50"><p class="entry-hint">이름을 바꿔도 안에 있는 준비물과 체크 표시는 유지돼.</p><div class="dialog-actions"><button type="button" id="cancelRenameCategory">취소</button><button class="primary">저장</button></div></form></dialog>');
let categoryRename=null;
const editableCategoryRender=render;
render=function(){editableCategoryRender();if(mode==='home')return;const sections=$('items').querySelectorAll('.category-group');sections.forEach((section,i)=>{section.querySelector('.category-heading h3').insertAdjacentHTML('afterend',`<button class="category-rename" data-rename-parent="${i}" aria-label="${esc(displayedGroups[i].name)} 카테고리 수정">수정</button>`);const subNames=[...displayedGroups[i].children.keys()].filter(Boolean);section.querySelectorAll('.sub-heading').forEach((heading,j)=>{heading.querySelector('h4').insertAdjacentHTML('afterend',`<button class="category-rename" data-rename-sub="${i}" data-sub-name="${esc(subNames[j])}" aria-label="${esc(subNames[j])} 하위 카테고리 수정">수정</button>`);});});};
const editableCategoryClick=$('items').onclick;
$('items').onclick=e=>{const parent=e.target.closest('[data-rename-parent]'),sub=e.target.closest('[data-rename-sub]');if(!parent&&!sub)return editableCategoryClick(e);const group=displayedGroups[Number(parent?parent.dataset.renameParent:sub.dataset.renameSub)];categoryRename={parent:group.name,sub:sub?sub.dataset.subName:null};$('renameCategoryTitle').textContent=sub?'하위 카테고리 수정':'준비물 카테고리 수정';$('renameCategoryInput').value=categoryRename.sub||categoryRename.parent;$('renameCategoryDialog').showModal();$('renameCategoryInput').focus();$('renameCategoryInput').select();};
$('cancelRenameCategory').onclick=()=>$('renameCategoryDialog').close();
$('renameCategoryForm').onsubmit=e=>{e.preventDefault();const next=$('renameCategoryInput').value.trim();if(!next)return;const {parent,sub}=categoryRename;if(next===(sub||parent)){$('renameCategoryDialog').close();return}const group=displayedGroups.find(g=>g.name===parent);const conflict=sub?group.children.has(next):displayedGroups.some(g=>g.name===next);if(conflict){$('renameCategoryInput').setCustomValidity('이미 있는 이름이야. 다른 이름을 입력해 줘.');$('renameCategoryInput').reportValidity();return;}
 const affected=(view==='common'?data.common:[...data.common,...place().items]).filter(item=>parentName(item)===parent&&(sub===null||(item.subcategory||'')===sub));
 const registryKeys=new Set([treeKey()]);if(affected.some(isCommon))registryKeys.add('common');
 for(const k of registryKeys){const entries=data.categoryTrees[k]||[];const source=entries.find(c=>c.name===parent);if(source){if(sub===null)source.name=next;else source.children=source.children.map(c=>c===sub?next:c);}}
 affected.forEach(item=>{if(sub===null)item.category=next;else item.subcategory=next});
 save();render();$('renameCategoryDialog').close();};
$('renameCategoryInput').oninput=()=>$('renameCategoryInput').setCustomValidity('');
$('renameCategoryForm').querySelector('.dialog-actions').insertAdjacentHTML('afterbegin','<button type="button" id="deleteCategory" class="danger">카테고리 삭제</button>');
document.body.insertAdjacentHTML('beforeend','<dialog id="deleteCategoryDialog"><form id="deleteCategoryForm"><h2>카테고리 삭제</h2><p id="deleteCategoryDescription"></p><label for="categoryDeleteAction">안의 준비물은 어떻게 할까?</label><select id="categoryDeleteAction"><option value="move">다른 카테고리로 옮기기</option><option value="remove">준비물도 함께 삭제하기</option></select><label id="categoryDestinationLabel" for="categoryDestination">옮길 카테고리</label><input id="categoryDestination" maxlength="50" list="categorySuggestions" placeholder="예: 기타 준비물"><p id="deleteCategoryError" role="alert"></p><div class="dialog-actions"><button type="button" id="cancelDeleteCategory">취소</button><button class="danger">삭제하기</button></div></form></dialog>');
const affectedCategoryItems=()=>{const {parent,sub}=categoryRename;return (view==='common'?data.common:[...data.common,...place().items]).filter(x=>parentName(x)===parent&&(sub===null||(x.subcategory||'')===sub));};
$('deleteCategory').onclick=()=>{const count=affectedCategoryItems().length;const common=affectedCategoryItems().some(isCommon);$('deleteCategoryDescription').textContent=`‘${categoryRename.sub||categoryRename.parent}’ 카테고리와 안의 준비물 ${count}개를 정리해.${common?' 공통 준비물 변경은 모든 장소에 반영돼.':''}`;$('categoryDeleteAction').value='move';$('categoryDestination').value=categoryRename.parent==='기타 준비물'?'정리할 준비물':'기타 준비물';$('categoryDestination').hidden=$('categoryDestinationLabel').hidden=false;$('deleteCategoryError').textContent='';$('renameCategoryDialog').close();$('deleteCategoryDialog').showModal();};
$('categoryDeleteAction').onchange=()=>{$('categoryDestination').hidden=$('categoryDestinationLabel').hidden=$('categoryDeleteAction').value==='remove'};
$('cancelDeleteCategory').onclick=()=>{$('deleteCategoryDialog').close();$('renameCategoryDialog').showModal()};
$('deleteCategoryForm').onsubmit=e=>{e.preventDefault();const {parent,sub}=categoryRename;const move=$('categoryDeleteAction').value==='move';const destination=$('categoryDestination').value.trim();if(move&&(!destination||(sub===null&&destination===parent))){$('deleteCategoryError').textContent='옮길 카테고리를 다른 이름으로 입력해 줘.';return}const items=affectedCategoryItems(),ids=new Set(items.map(x=>x.id));const keys=new Set([treeKey()]);if(items.some(isCommon))keys.add('common');for(const k of keys){const entries=data.categoryTrees[k]||[];if(sub===null)data.categoryTrees[k]=entries.filter(c=>c.name!==parent);else{const entry=entries.find(c=>c.name===parent);if(entry)entry.children=entry.children.filter(s=>s!==sub)}}if(move){items.forEach(x=>{x.category=destination;if(sub!==null)x.subcategory=''});if(items.length){rememberCategory(destination);items.forEach(x=>{if(x.subcategory)rememberCategory(destination,x.subcategory)})}}else{data.common=data.common.filter(x=>!ids.has(x.id));place().items=place().items.filter(x=>!ids.has(x.id));Object.keys(data.checks).forEach(k=>{if([...ids].some(id=>k.endsWith(id)))delete data.checks[k]})}save();render();$('deleteCategoryDialog').close()};
render();
