(() => {
'use strict';
const C=COPY,B=C.buttons,E=C.editor,M=ChecklistModel,$=s=>document.querySelector(s),uid=M.uid;
const esc=s=>String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={home:'M3 11 12 3l9 8M5 10v11h5v-7h4v7h5V10',bag:'M5 7h14v14H5zM9 7V3h6v4M8 7v14M16 7v14',plane:'m3 13 7-3V3l3-1 1 8 7 4v3l-7-2v5l-2 2-2-7-7 1z',mountain:'m2 21 7-15 4 7 3-5 6 13zM6 12l3 2 2-3',shopping:'M5 7h14l2 14H3zM8 8V5a4 4 0 0 1 8 0v3',case:'M3 7h18v14H3zM8 7V3h8v4M3 12h18M10 11v3h4v-3',tent:'m2 21 10-18 10 18zM8 21l4-9 4 9',water:'M2 10q3-4 6 0t6 0 6 0M2 17q3-4 6 0t6 0 6 0',pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0zM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0',key:'M14 3a6 6 0 1 1-4 10L3 21H1v-4l7-8a6 6 0 0 1 6-6zM15 7h.01',heart:'M12 21S1 14 2 7c1-6 8-6 10-1 2-5 9-5 10 1 1 7-10 14-10 14z',book:'M3 3h8l1 2 1-2h8v17h-8l-1 1-1-1H3zM12 5v15',mic:'M9 4a3 3 0 0 1 6 0v8a3 3 0 0 1-6 0zM5 10v2a7 7 0 0 0 14 0v-2M12 19v4M8 23h8',plus:'M12 5v14M5 12h14',chevron:'m9 5 7 7-7 7',down:'m5 9 7 7 7-7',edit:'m4 16 12-12 4 4L8 20H4zM14 6l4 4',grip:'M8 5h.01M16 5h.01M8 12h.01M16 12h.01M8 19h.01M16 19h.01',close:'m5 5 14 14M5 19 19 5',arrow:'M4 12h16m-6-6 6 6-6 6',reset:'M4 10a8 8 0 1 1 1 8M4 3v7h7',up:'m5 15 7-7 7 7'};
paths.eyeoff='M3 3l18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 4.2A10.8 10.8 0 0 1 12 4c5.5 0 9.5 5.8 9.5 5.8a17 17 0 0 1-3.3 3.8M6.5 6.5C3.9 8.2 2.5 10 2.5 10S6.5 16 12 16c1.2 0 2.3-.2 3.3-.6';
const icon=(n,cl='')=>`<svg class="icon ${cl}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[n]||paths.bag}"/></svg>`;
const btn=(action,text,cls='',attrs='')=>`<button type="button" data-action="${action}" class="${cls}" ${attrs}>${text}</button>`;
const icons=['bag','plane','mountain','shopping','case','tent','water','home','key','book','heart'];
const colors=['#285e49','#a9c2ac','#eed9ae','#e8bdb8','#b9d3df','#cec5df'];
let storageError=false;
let raw=null;try{raw=localStorage.getItem('chaenggim-v1');}catch(e){storageError=true;}
let data;
try{
 const saved=raw?JSON.parse(raw):null;
 if(saved&&!Array.isArray(saved.places))throw Error('invalid');
 data=M.migrate(saved||{places:C.defaults.places.map((name,i)=>({id:uid(),name,icon:icons[i],items:[]})),common:[],locations:[]},C);
 if(raw&&!localStorage.getItem('chaenggim-before-final'))localStorage.setItem('chaenggim-before-final',raw);
}catch(e){storageError=true;data=M.migrate({places:[],locations:[],common:[]},C);}
let page='home',selected=null,filter='all',collapsed=false,importOpen=false,recognition=null,editing=null;
try{const v=JSON.parse(sessionStorage.getItem('chaenggim-view')||'null');if(v){page=v.page;selected=v.selected;}}catch(e){}
if(page==='detail'&&!data.places.some(p=>p.id===selected))page='packing';
function notify(s){$('#notice').textContent=s;$('#notice').classList.add('show');clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('#notice').classList.remove('show'),3500);}
function save(){if(storageError){notify(C.messages.corrupt);return false;}try{localStorage.setItem('chaenggim-v1',JSON.stringify(data));return true;}catch(e){notify(C.messages.storage);return false;}}
const place=()=>data.places.find(p=>p.id===selected);
const items=p=>[...data.common.filter(i=>!(p.hiddenCommon||[]).includes(i.id)),...p.items];
const isShared=i=>data.common.includes(i);
const checked=(p,i)=>isShared(i)?!!data.checks[p.id+i.id]:!!i.checked;
const stats=p=>{const all=items(p);return {total:all.length,done:all.filter(i=>checked(p,i)).length};};
function navigate(p,id){page=p;selected=p==='common'?(data.places[0]?.id||null):(id||null);filter='all';importOpen=false;if(p==='detail'){data.recent=[id,...data.recent.filter(x=>x!==id)].slice(0,6);save();}sessionStorage.setItem('chaenggim-view',JSON.stringify({page,selected}));render();window.scrollTo(0,0);}
function input(placeholder){return `<form class="command-form"><input name="command" aria-label="${esc(placeholder)}" placeholder="${esc(placeholder)}" autocomplete="off" required maxlength="500"><button type="submit" class="send" aria-label="${B.submit}">${icon('arrow')}</button>${btn('mic',icon('mic'),'mic',`aria-label="${B.mic}"`)}</form>`;}
function sidebar(){return `<aside class="sidebar"><a class="brand" href="#" data-action="home"><img src="assets/home.svg" alt=""><strong>${C.brand.name}</strong><small>${C.brand.footer}</small></a><nav>${btn('home',icon('home')+C.nav.home,page==='home'?'active':'') }<div class="nav-packing">${btn('packing',icon('bag')+C.nav.packing,['packing','detail','common'].includes(page)?'active':'')}${btn('collapse',icon('down'),collapsed?'folded':'',`aria-label="${C.nav.toggle}" aria-expanded="${!collapsed}"`)}</div><div class="place-nav" ${collapsed?'hidden':''}>${btn('common',icon('bag')+C.packing.shared,page==='common'?'selected':'')} ${data.places.map(p=>`<div class="nav-row" draggable="true" data-drag="place" data-id="${p.id}"><span class="grip">${icon('grip')}</span>${btn('detail',esc(p.name),page==='detail'&&selected===p.id?'selected':'',`data-id="${p.id}"`)}</div>`).join('')}${btn('new-place',icon('plus')+B.addCategory,'text')}</div><div class="nav-packing">${btn('locations',icon('pin')+C.nav.locations,page==='locations'?'active':'')}</div><div class="place-nav" ${page==='locations'?'':'hidden'}>${btn('filter',B.all,filter==='all'?'selected':'',`data-id="all"`)}${data.locationCategories.map(c=>`<div class="nav-row" draggable="true" data-drag="location-category" data-id="${c.id}"><span class="grip">${icon('grip')}</span>${btn('filter',esc(c.name),filter===c.id?'selected':'',`data-id="${c.id}"`)}</div>`).join('')}${btn('new-location-category',icon('plus')+B.addCategory,'text')}</div></nav><div class="sidebar-footer"><img src="assets/cat.png" alt=""><p>${C.brand.footer}</p></div></aside>`;}
function head(title,subtitle,description,type,action=''){return `<header class="page-head"><div class="head-title">${icon(type)}<h1>${esc(title)}</h1>${action}</div>${subtitle?`<h2>${esc(subtitle)}</h2>`:''}${description?`<p>${esc(description)}</p>`:''}</header>`;}
function home(){return `<section class="hero"><div><h1>${C.brand.name}</h1><h2>${esc(C.brand.headline)}</h2><p>${esc(C.brand.description)}</p></div><img class="hero-cat" src="assets/cat.png" alt="${C.brand.cat}"></section>${input(C.home.input)}<p class="input-example">${C.home.example}</p><section class="recent"><h3>${C.home.recent}</h3><div class="chips">${(data.recent.length?data.recent.map(id=>data.places.find(p=>p.id===id)).filter(Boolean):data.places.slice(0,6)).map(p=>btn('detail',icon(p.icon)+esc(p.name),'chip',`data-id="${p.id}"`)).join('')}</div></section><div class="entry-cards">${[['packing','bag',C.nav.packing,C.packing.headline,C.packing.description],['locations','pin',C.nav.locations,C.itemLocation.headline,C.itemLocation.description]].map(([action,i,t,h,d])=>btn(action,`<span class="entry-icon">${icon(i)}</span><span><strong>${t}</strong><span>${esc(h)}<br>${esc(d)}</span></span>${icon('chevron')}`,'entry-card')).join('')}</div>`;}
function mobileCategories(){return `<div class="mobile-categories"><div class="chips">${data.places.map(p=>btn('detail',esc(p.name),'chip '+(p.id===selected?'active':''),`data-id="${p.id}"`)).join('')}</div>${btn('all-places',icon('down'),'',`aria-label="${B.allCategories}"`)}</div>`;}
function packing(){const base=data.places[0];const sharedStats=base?{total:data.common.length,done:data.common.filter(i=>checked(base,i)).length}:{total:0,done:0};const sharedCard=`<article class="place-card shared-place-card"><div class="place-card-top">${btn('common',icon('bag')+`<strong>${esc(C.packing.shared)}</strong>`,'place-open')}</div>${btn('common',`<span>${sharedStats.done} / ${sharedStats.total} ${C.packing.done}</span>${icon('chevron')}<progress value="${sharedStats.done}" max="${sharedStats.total||1}"></progress><small>${esc(data.common.slice(0,4).map(i=>i.name).join(', '))}</small>`,'card-body')}<small class="shared-hint">${esc(C.packing.sharedHint)}</small></article>`;return `${head(C.nav.packing,C.packing.headline,C.packing.description,'bag',btn('new-place',icon('plus')+B.newCategory,'primary'))}${mobileCategories()}<div class="place-grid">${sharedCard}${data.places.map(p=>{const s=stats(p);return `<article style="--category-color:${esc(p.color||'#285e49')}" class="place-card" draggable="true" data-drag="place" data-id="${p.id}"><div class="place-card-top"><span class="grip">${icon('grip')}</span>${btn('detail',icon(p.icon)+`<strong>${esc(p.name)}</strong>`,'place-open',`data-id="${p.id}"`)}${btn('edit-place',icon('edit'),'icon-button',`data-id="${p.id}" aria-label="${esc(p.name)} ${B.edit}"`)}</div>${btn('detail',`<span>${s.done} / ${s.total} ${C.packing.done}</span>${icon('chevron')}<progress value="${s.done}" max="${s.total||1}"></progress><small>${esc(items(p).slice(0,4).map(i=>i.name).join(', '))}</small>`,'card-body',`data-id="${p.id}"`)}<div class="order-tools">${moveButtons('place',p.id)}</div></article>`;}).join('')||`<p class="empty">${C.packing.emptyCategories}</p>`}</div>`;}
function moveButtons(kind,id){return btn('move',icon('up'),'icon-button',`data-kind="${kind}" data-id="${esc(id)}" data-dir="-1" aria-label="${B.up}"`)+btn('move',icon('down'),'icon-button',`data-kind="${kind}" data-id="${esc(id)}" data-dir="1" aria-label="${B.down}"`);}
function groupList(p){const own=p.groups||[];return data.common.length?['@common',...own]:own;}
function detail(){const p=place();if(!p)return packing();const s=stats(p);return `${btn('packing',icon('chevron')+B.back,'back')}${head(p.name,'','',''+p.icon,btn('edit-place',icon('edit')+B.edit,'text',`data-id="${p.id}"`))}${mobileCategories()}<div class="progress-top"><span>${s.done} / ${s.total} ${C.packing.done}</span>${btn('reset',icon('reset')+B.reset,'subtle')}</div><progress value="${s.done}" max="${s.total||1}"></progress><div class="detail-list">${groupList(p).map((g,index)=>{const shared=g==='@common',list=shared?data.common:p.items.filter(i=>i.category===g);return `<section class="item-group"><div class="group-head"><h3>${esc(shared?C.packing.shared:g)}</h3>${shared?'':btn('edit-group',B.edit,'text',`data-group="${esc(g)}"`)}${btn('new-item',icon('plus')+B.addItem,'text',`data-group="${esc(g)}"`)}</div>${shared?`<p class="shared-hint">${C.packing.sharedHint}<span class="shared-hint-action">${icon('eyeoff')}<span>이 장소에서만 해당 항목 제외</span></span></p>`:''}${list.map(i=>`<div class="item-row ${checked(p,i)?'checked':''}" draggable="true" data-drag="item" data-id="${i.id}"><span class="grip">${icon('grip')}</span><label><input type="checkbox" data-check="${i.id}" ${checked(p,i)?'checked':''}><span>${esc(i.name)}</span></label><div class="row-tools">${moveButtons('item',i.id)}${shared?btn('hide-common',icon('eyeoff'),'icon-button hide-common-button',`data-id="${i.id}" aria-label="${esc(i.name)} 이 장소에서 숨기기"`):''}${btn('delete-item',icon('close'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.remove}"`)}${btn('edit-item',icon('edit'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.edit}"`)}</div></div>`).join('')||`<p class="empty compact">${esc(C.packing.empty)}</p>`}</section>`;}).join('')||`<p class="empty">${esc(C.packing.empty)}</p>`}</div><div class="group-actions">${btn('new-group',icon('plus')+B.addGroup,'subtle')}${btn('toggle-import',C.packing.import,'text',`aria-expanded="${importOpen}"`)}</div>${importOpen?importPanel():''}<div class="detail-input">${input(C.packing.input)}${btn('new-item',icon('plus')+B.addItem,'subtle')}</div>`;}
function importPanel(){const p=place();return `<section class="import-panel"><h3>${C.packing.pickImport}</h3>${data.places.filter(x=>x.id!==p.id&&x.groups.length).map(x=>`<div><h4>${esc(x.name)}</h4><div class="chips">${x.groups.map(g=>btn('import-group',`${esc(g)} <small>${x.items.filter(i=>i.category===g).length}</small>`,'chip',`data-id="${x.id}" data-group="${esc(g)}"`)).join('')}</div></div>`).join('')||`<p>${C.packing.importEmpty}</p>`}${btn('toggle-import',B.cancel,'text')}</section>`;}
function locations(){const list=data.locations.filter(i=>filter==='all'||i.locationCategory===filter);return `${head(C.nav.locations,C.itemLocation.headline,C.itemLocation.description,'pin',btn('new-object',icon('plus')+B.addObject,'primary'))}<div class="filter-bar chips">${btn('filter',B.all,'chip '+(filter==='all'?'active':''),'data-id="all"')}${data.locationCategories.map(c=>btn('filter',esc(c.name),'chip '+(filter===c.id?'active':''),`data-id="${c.id}"`)).join('')}${btn('new-location-category',icon('plus'),'chip',`aria-label="${E.objectCategory}"`)}${filter!=='all'?btn('edit-location-category',icon('edit')+B.edit,'text'):''}</div>${input(C.itemLocation.input)}<p class="input-example">${C.itemLocation.example}</p><div class="location-table"><div class="location-header"><span>${C.itemLocation.name}</span><span>${C.itemLocation.location}</span><span>${C.itemLocation.category}</span><span>${C.itemLocation.memo}</span><span>${C.itemLocation.updated}</span><span></span></div>${list.map(i=>`<div class="location-row"><strong>${icon('pin')}${esc(i.name)}</strong><span class="object-position">${esc(i.location)}</span><span class="object-category">${esc((data.locationCategories.find(c=>c.id===i.locationCategory)||{}).name||'')}</span><span class="object-memo">${esc(i.memo)}</span><small>${i.updated?new Date(i.updated).toLocaleDateString('ko-KR'):''}</small>${btn('delete-object',icon('close'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.remove}"`)}${btn('edit-object',icon('edit'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.edit}"`)}</div>`).join('')||`<p class="empty">${esc(C.itemLocation.empty)}</p>`}</div>`;}
function commonPage(){const p=data.places[0];if(!p)return packing();const list=data.common;return `${head(C.packing.shared,C.packing.headline,C.packing.sharedHint,'bag',btn('new-item',icon('plus')+B.addItem,'primary',`data-group="@common"`))}<p class="shared-hint">${C.packing.sharedHint}<span class="shared-hint-action">${icon('eyeoff')}<span>이 장소에서만 해당 항목 제외</span></span></p><div class="detail-list"><section class="item-group"><div class="group-head"><h3>${esc(C.packing.shared)}</h3></div>${list.map(i=>`<div class="item-row" data-id="${i.id}"><label><span>${esc(i.name)}</span></label><div class="row-tools">${btn('delete-item',icon('close'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.remove}"`)}${btn('edit-item',icon('edit'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.edit}"`)}</div></div>`).join('')||`<p class="empty compact">${esc(C.packing.empty)}</p>`}</section></div>${input(C.packing.input)}`;}
function render(){document.title=C.brand.name;$('#app').innerHTML=`${sidebar()}<div class="mobile-header"><img src="assets/home.svg" alt=""><strong>${C.brand.name}</strong></div><main id="main">${page==='home'?home():page==='packing'?packing():page==='detail'?detail():page==='common'?commonPage():locations()}<footer class="main-footer">${C.brand.footer}</footer></main><nav class="bottom-nav">${[['home','home',C.nav.home],['packing','bag',C.nav.mobilePacking],['locations','pin',C.nav.mobileLocations]].map(([a,i,t])=>btn(a,icon(i)+`<span>${t}</span>`,(page===a||(a==='packing'&&['detail','common'].includes(page)))?'active':'',`aria-current="${page===a||(a==='packing'&&['detail','common'].includes(page))?'page':'false'}"`)).join('')}</nav>`;}
function field(name,label,value='',extra=''){return `<label class="field">${esc(label)}<input name="${name}" value="${esc(value)}" required maxlength="100" ${extra}></label>`;}
function select(name,label,options,value){return `<label class="field">${esc(label)}<select name="${name}">${options.map(o=>`<option value="${esc(o.id)}" ${o.id===value?'selected':''}>${esc(o.name)}</option>`).join('')}</select></label>`;}
function modal(title,body,onSubmit,remove){const d=$('#editor');d.innerHTML=`<form id="edit-form"><div class="modal-head"><h2>${esc(title)}</h2>${btn('close',icon('close'),'icon-button',`aria-label="${B.close}"`)}</div>${body}<div class="dialog-actions">${remove?btn('delete',B.remove,'danger'):''}${btn('close',B.cancel,'subtle')}<button class="primary" type="submit">${B.save}</button></div></form>`;d.querySelector('form').onsubmit=e=>{e.preventDefault();onSubmit(new FormData(e.currentTarget));};if(remove)d.querySelector('[data-action="delete"]').onclick=remove;if(!d.open)d.showModal();}
function close(){$('#editor').close();}
function confirmDialog(message,fn,label=B.remove){modal(label===B.reset?B.reset:E.confirm,`<p class="confirm-message">${esc(message)}</p>`,()=>{fn();close();save();render();notify(label===B.reset?C.messages.reset:C.messages.removed);});$('#editor button[type="submit"]').textContent=label;$('#editor button[type="submit"]').className=label===B.remove?'danger solid':'primary';}
function categoryEditor(p){let chosen=p?.icon||'bag',color=p?.color||colors[0];modal(p?E.editCategory:B.newCategory,field('name',E.categoryName,p?.name||'',`placeholder="${E.categoryHint}"`)+`<fieldset><legend>${E.icon}</legend><div class="icon-options">${icons.map(i=>`<label><input type="radio" name="icon" value="${i}" ${i===chosen?'checked':''}><span title="${C.icons[i]}">${icon(i)}</span></label>`).join('')}</div></fieldset><fieldset><legend>${E.color}</legend><div class="color-options">${colors.map(c=>`<label><input type="radio" name="color" value="${c}" ${c===color?'checked':''}><span style="background:${c}"></span></label>`).join('')}</div></fieldset>`,f=>{const name=f.get('name').trim();if(!name)return; if(data.places.some(x=>x!==p&&x.name===name))return notify(E.duplicate);if(p)Object.assign(p,{name,icon:f.get('icon'),color:f.get('color')});else data.places.push({id:uid(),name,icon:f.get('icon'),color:f.get('color'),items:[],groups:[]});save();close();render();notify(C.messages.saved);},p?()=>confirmDialog(E.deleteCategory,()=>{data.places=data.places.filter(x=>x!==p);if(selected===p.id){page='packing';selected=null;}data.recent=data.recent.filter(id=>id!==p.id);}):null);}
function itemEditor(item,group){const p=place();const g=item?(isShared(item)?'@common':item.category):group||p.groups[0]||C.defaults.base;
const opts=[{id:'@common',name:C.packing.shared},...[...new Set([...p.groups,g])].filter(x=>x!=='@common').map(name=>({id:name,name}))];
modal(item?E.editItem:B.addItem,field('name',E.itemName,item?.name||'')+select('group',C.packing.group,opts,g),f=>{const name=f.get('name').trim(),group=f.get('group');if(!name)return;let target=group==='@common'?data.common:p.items;if(item){const wasShared=isShared(item);if(wasShared!==(group==='@common')){if(wasShared)data.common=data.common.filter(x=>x!==item);else p.items=p.items.filter(x=>x!==item);target.push(item);}item.name=name;item.category=group;}else target.push({id:uid(),name,category:group,checked:false});if(group!=='@common'&&!p.groups.includes(group))p.groups.push(group);save();close();render();notify(C.messages.saved);},item?()=>confirmDialog(isShared(item)?E.sharedDelete:E.deleteItem,()=>{data.common=data.common.filter(x=>x!==item);p.items=p.items.filter(x=>x!==item);}):null);}
function groupEditor(g){const p=place();modal(g?E.editCategory:B.addGroup,field('name',E.categoryName,g||''),f=>{const n=f.get('name').trim();if(!n)return;if(p.groups.some(x=>x!==g&&x===n)||n===C.packing.shared)return notify(E.duplicate);if(g){p.groups[p.groups.indexOf(g)]=n;p.items.filter(i=>i.category===g).forEach(i=>i.category=n);}else p.groups.push(n);save();close();render();},g?()=>confirmDialog(E.deleteCategory,()=>{p.groups=p.groups.filter(x=>x!==g);p.items=p.items.filter(x=>x.category!==g);}):null);}
function objectEditor(item,prefill){const i=item||prefill||{};if(!data.locationCategories.length)data.locationCategories=C.defaults.locationCategories.map(name=>({id:uid(),name}));modal(item?E.editObject:E.newObject,field('name',C.itemLocation.name,i.name||'')+field('location',C.itemLocation.location,i.location||'')+select('category',C.itemLocation.category,data.locationCategories,i.locationCategory||(filter!=='all'?filter:data.locationCategories[0].id))+`<label class="field">${C.itemLocation.memo}<textarea name="memo" maxlength="500">${esc(i.memo||'')}</textarea></label>`,f=>{const name=f.get('name').trim(),location=f.get('location').trim();if(!name||!location)return;const v={name,location,locationCategory:f.get('category'),memo:f.get('memo').trim(),updated:new Date().toISOString()};if(item)Object.assign(item,v);else data.locations.push({id:uid(),...v});save();close();render();notify(C.messages.saved);},item?()=>confirmDialog(E.deleteItem,()=>data.locations=data.locations.filter(x=>x!==item)):null);}
function locationCategoryEditor(c){modal(c?E.editCategory:E.objectCategory,field('name',E.categoryName,c?.name||''),f=>{const n=f.get('name').trim();if(!n)return;if(data.locationCategories.some(x=>x!==c&&x.name===n))return notify(E.duplicate);if(c)c.name=n;else data.locationCategories.push({id:uid(),name:n});save();close();render();},c?()=>confirmDialog(E.deleteObjectCategory,()=>{data.locations=data.locations.filter(x=>x.locationCategory!==c.id);data.locationCategories=data.locationCategories.filter(x=>x!==c);filter='all';}):null);}
function addNames(id,names){const p=data.places.find(x=>x.id===id);if(!p)return;const group=p.groups[0]||C.defaults.base;if(!p.groups.includes(group))p.groups.push(group);const existing=new Set(items(p).map(x=>x.name));const list=names.filter(n=>!existing.has(n));p.items.push(...list.map(name=>({id:uid(),name,category:group,checked:false})));save();close();navigate('detail',id);notify(list.length?C.messages.added:C.messages.duplicateItem);}
function addCommonNames(names){const existing=new Set(data.common.map(x=>x.name));const list=names.filter(n=>!existing.has(n));data.common.push(...list.map(name=>({id:uid(),name,category:'@common',checked:false})));save();close();render();notify(list.length?C.messages.added:C.messages.duplicateItem);}
function deleteCommonByCommand(query){const all=M.isDeleteAll(query),result=all?{ids:data.common.map(i=>i.id),missing:[]}:M.matchDeletion(query,data.common);if(!result.ids.length)return notify(all?E.emptyOwn:E.notFound);const targets=data.common.filter(i=>result.ids.includes(i.id));confirmDialog([E.deleteTargets,...targets.map(i=>'• '+i.name),E.deleteCommon].join('\n'),()=>{data.common=data.common.filter(i=>!result.ids.includes(i.id));});}
function deleteByCommand(id,query){
 const p=data.places.find(x=>x.id===id);if(!p)return;
 const all=M.isDeleteAll(query);
 const result=all?{ids:p.items.map(i=>i.id),missing:[]}:M.matchDeletion(query,items(p));
 if(!result.ids.length){notify(all?E.emptyOwn:E.notFound);return;}
 const targets=items(p).filter(i=>result.ids.includes(i.id));
 const lines=[p.name,E.deleteTargets,...targets.map(i=>'• '+i.name+(isShared(i)?' ('+C.packing.shared+')':''))];
 if(all)lines.push(E.keepCommon);
 if(targets.some(isShared))lines.push(E.deleteCommon);
 if(result.missing.length)lines.push(E.unmatched+' '+result.missing.join(', '));
 confirmDialog(lines.join('\n'),()=>{p.items=p.items.filter(i=>!result.ids.includes(i.id));data.common=data.common.filter(i=>!result.ids.includes(i.id));});
}
function editByCommand(id,command){
 const p=data.places.find(x=>x.id===id);if(!p)return;
 const targets=items(p).filter(i=>i.name.trim()===command.oldName);
 if(!targets.length)return notify(E.notFound);
 if(targets.length!==1)return notify(E.ambiguousEdit);
 const item=targets[0];
 modal(E.commandEdit,'<p>'+esc(p.name)+'<br>'+esc(E.renamePreview)+'<br>'+esc(item.name)+' → '+esc(command.newName)+(isShared(item)?'<br>'+esc(C.packing.sharedHint):'')+'</p>',()=>{item.name=command.newName;save();close();render();notify(C.messages.saved);});
}
function locationCommand(raw){const s=raw.trim().replace(/[.!?。]+$/,'');const del=s.match(/^(.+?)(?:을|를)?\s*(?:삭제|지워|빼)(?:해줘|해주세요)?$/);if(del){const item=data.locations.find(x=>x.name===del[1].trim());if(!item)return notify(E.notFound);return confirmDialog(`${item.name}\n${item.location}\n${E.deleteTargets}`,()=>{data.locations=data.locations.filter(x=>x!==item);});}const edit=s.match(/^(.+?)(?:을|를)\s+(.+?)(?:으로|로)\s*(?:수정|변경)(?:해줘|해주세요)?$/);if(edit){const item=data.locations.find(x=>x.name===edit[1].trim());if(!item)return notify(E.notFound);return objectEditor(item,{...item,name:edit[2].trim()});}const parsed=M.parseLocation(raw);if(!parsed.name||!parsed.location)return notify(C.messages.chooseLocation);const category=filter!=='all'?filter:(data.locationCategories[0]?.id||'');const existing=data.locations.find(x=>x.name===parsed.name);if(existing){existing.location=parsed.location;existing.locationCategory=existing.locationCategory||category;existing.updated=new Date().toISOString();}else data.locations.push({id:uid(),name:parsed.name,location:parsed.location,locationCategory:category,memo:'',updated:new Date().toISOString()});save();render();notify(C.messages.saved);}
function processCommand(raw){if(!raw.trim())return;if(page==='locations'){locationCommand(raw);return;}
const command=M.parseCommand(raw,data.places,page==='detail'?selected:null);
if(command.type==='invalid-edit')return notify(E.invalidEdit);
if(command.type==='rename-category'){
 const p=data.places.find(x=>x.id===command.place);
 if(!p)return notify(E.notFound);
 if(!command.newName)return notify(E.invalidEdit);
 if(data.places.some(x=>x!==p&&x.name===command.newName))return notify(E.duplicate);
 modal(E.editCategory,'<p>'+esc(E.renamePreview)+'<br>'+esc(p.name)+' → '+esc(command.newName)+'</p>',()=>{p.name=command.newName;save();close();render();notify(C.messages.saved);});return;
}
if(command.type==='edit'){
 if(command.place)editByCommand(command.place,command);
 else modal(E.editChoose,select('place',E.categoryName,data.places,data.places[0]?.id),f=>editByCommand(f.get('place'),command));
 return;
}
if(command.type==='delete'){
 if(page==='common'){deleteCommonByCommand(command.query);return;}
 if(!command.query)return notify(E.notFound);
 if(command.place)deleteByCommand(command.place,command.query);
 else modal(E.deleteChoose,'<p>'+esc(command.query)+'</p>'+select('place',E.categoryName,data.places,data.places[0]?.id),f=>deleteByCommand(f.get('place'),command.query));
 return;
}
if(command.type==='category'){const exists=data.places.find(p=>p.name===command.name);if(exists){navigate('detail',exists.id);notify(E.duplicate);return;}const p={id:uid(),name:command.name,icon:'bag',items:[],groups:[]};data.places.push(p);save();navigate('detail',p.id);notify(C.messages.added);return;}
if(!command.names.length)return notify(C.messages.nothing);
if(page==='common'){addCommonNames(command.names);return;}
if(command.place){addNames(command.place,command.names);return;}
modal(E.choose,`<p>${esc(command.names.join(', '))}</p>`+select('place',E.categoryName,data.places,data.places[0]?.id),f=>addNames(f.get('place'),command.names));}
function startVoice(){
 if(recognition){recognition.stop();return;}
 const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;
 const status=message=>{notify(message);let el=document.querySelector('.voice-status');if(!el){el=document.createElement('p');el.className='voice-status input-example';el.setAttribute('role','status');document.querySelector('.command-form')?.after(el);}if(el)el.textContent=message;};
 if(!Speech){status(C.messages.unsupported);return;}
 let received=false,failed=false;
 try{
  recognition=new Speech();recognition.lang='ko-KR';recognition.interimResults=false;recognition.maxAlternatives=1;
  recognition.onstart=()=>{document.querySelectorAll('.mic').forEach(b=>{b.classList.add('listening');b.setAttribute('aria-label',B.stop);});status(C.messages.listening);};
  recognition.onresult=e=>{received=true;const text=e.results[0][0].transcript;const field=$('.command-form input');if(field)field.value=text;processCommand(text);};
  recognition.onerror=e=>{failed=true;const errors={'not-allowed':'voiceDenied','service-not-allowed':'voiceUnavailable','network':'voiceNetwork','audio-capture':'voiceCapture','no-speech':'noSpeech','language-not-supported':'voiceLanguage'};status(C.messages[errors[e.error]||'voiceError']);};
  recognition.onend=()=>{recognition=null;document.querySelectorAll('.mic').forEach(b=>{b.classList.remove('listening');b.setAttribute('aria-label',B.mic);});if(!received&&!failed)status(C.messages.noSpeech);};
  recognition.start();
 }catch(e){recognition=null;status(C.messages.voiceError);}
}
function reorder(kind,id,targetIndex){let arr=kind==='place'?data.places:kind==='location-category'?data.locationCategories:(data.common.some(x=>x.id===id)?data.common:place()?.items);if(!arr)return;const from=arr.findIndex(x=>x.id===id);if(from<0||targetIndex<0||targetIndex>=arr.length)return;const [x]=arr.splice(from,1);arr.splice(targetIndex,0,x);save();render();}
document.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id,g=b.dataset.group;
if(['home','packing','locations','detail','common'].includes(a)){e.preventDefault();if(a==='common'){selected=data.places[0]?.id||null;navigate('common');}else navigate(a,id);}
else if(a==='collapse'){collapsed=!collapsed;render();}
else if(a==='new-place')categoryEditor();else if(a==='edit-place')categoryEditor(data.places.find(p=>p.id===id));
else if(a==='new-item'){if(page==='common'){const p=place();itemEditor(null,'@common');}else itemEditor(null,g);}else if(a==='edit-item'){if(page==='common'){const i=data.common.find(x=>x.id===id);selected=data.places[0]?.id||null;itemEditor(i);}else itemEditor(items(place()).find(x=>x.id===id));}else if(a==='hide-common'){const p=place();if(p){p.hiddenCommon=p.hiddenCommon||[];const n=p.hiddenCommon.indexOf(id);if(n<0)p.hiddenCommon.push(id);else p.hiddenCommon.splice(n,1);save();render();notify(C.messages.saved);}}else if(a==='delete-item'){const i=(page==='common'?data.common:items(place())).find(x=>x.id===id);if(i)confirmDialog(E.deleteItem,()=>{data.common=data.common.filter(x=>x!==i);data.places.forEach(p=>p.items=p.items.filter(x=>x!==i));});}
else if(a==='new-group')groupEditor();else if(a==='edit-group')groupEditor(g);
else if(a==='new-object')objectEditor();else if(a==='edit-object')objectEditor(data.locations.find(x=>x.id===id));
else if(a==='new-location-category')locationCategoryEditor();else if(a==='edit-location-category')locationCategoryEditor(data.locationCategories.find(c=>c.id===filter));
else if(a==='filter'){filter=id;render();}else if(a==='close')close();else if(a==='mic')startVoice();
else if(a==='reset')confirmDialog(E.reset,()=>{place().items.forEach(i=>i.checked=false);data.common.forEach(i=>data.checks[selected+i.id]=false);},B.reset);
else if(a==='toggle-import'){importOpen=!importOpen;render();}
else if(a==='import-group'){const source=data.places.find(p=>p.id===id),p=place();let name=g,n=2;while(p.groups.includes(name))name=g+' ('+(n++)+')';p.groups.push(name);p.items.push(...source.items.filter(i=>i.category===g).map(i=>({...i,id:uid(),category:name,checked:false})));importOpen=false;save();render();notify(C.messages.added);}
else if(a==='all-places'){modal(B.allCategories,`<div class="all-places">${data.places.map(p=>btn('choose-place',icon(p.icon)+esc(p.name),'subtle',`data-id="${p.id}"`)).join('')}</div>`,close);}
else if(a==='choose-place'){close();navigate('detail',id);}
else if(a==='move'){const arr=b.dataset.kind==='place'?data.places:(data.common.some(i=>i.id===id)?data.common:place().items);reorder(b.dataset.kind,id,arr.findIndex(x=>x.id===id)+Number(b.dataset.dir));}
});
document.addEventListener('submit',e=>{if(!e.target.matches('.command-form'))return;e.preventDefault();processCommand(new FormData(e.target).get('command'));});
document.addEventListener('change',e=>{if(!e.target.dataset.check)return;const p=place(),i=items(p).find(x=>x.id===e.target.dataset.check);if(isShared(i))data.checks[p.id+i.id]=e.target.checked;else i.checked=e.target.checked;save();render();});
let drag=null;document.addEventListener('dragstart',e=>{const el=e.target.closest('[data-drag]');if(!el)return;drag={kind:el.dataset.drag,id:el.dataset.id};e.dataTransfer.setData('text/plain',drag.id);e.dataTransfer.effectAllowed='move';});
document.addEventListener('dragover',e=>{const el=e.target.closest('[data-drag]');if(el&&drag&&el.dataset.drag===drag.kind)e.preventDefault();});
document.addEventListener('drop',e=>{const el=e.target.closest('[data-drag]');if(!el||!drag||el.dataset.drag!==drag.kind)return;e.preventDefault();let arr=drag.kind==='place'?data.places:drag.kind==='location-category'?data.locationCategories:(data.common.some(i=>i.id===drag.id)?data.common:place().items);const target=arr.findIndex(x=>x.id===el.dataset.id);reorder(drag.kind,drag.id,target);drag=null;});
window.addEventListener('storage',e=>{if(e.key==='chaenggim-v1'&&e.newValue){try{data=M.migrate(JSON.parse(e.newValue),C);if(page==='detail'&&!place())page='packing';render();}catch(e){notify(C.messages.corrupt);}}});
function commonPage(){const p=place()||data.places[0];const list=data.common;const done=p?list.filter(i=>checked(p,i)).length:0;return `${head(C.packing.shared,C.packing.headline,C.packing.sharedHint,'bag',btn('new-item',icon('plus')+B.addItem,'primary',`data-group="@common"`))}<div class="progress-top"><span>${done} / ${list.length} ${C.packing.done}</span>${btn('reset',icon('reset')+B.reset,'subtle')}</div><progress value="${done}" max="${list.length||1}"></progress><div class="detail-list"><section class="item-group"><div class="group-head"><h3>${esc(C.packing.shared)}</h3></div>${list.map(i=>`<div class="item-row ${checked(p,i)?'checked':''}" data-id="${i.id}"><label><input type="checkbox" data-check="${i.id}" ${checked(p,i)?'checked':''}><span>${esc(i.name)}</span></label><div class="row-tools">${btn('delete-item',icon('close'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.remove}"`)}${btn('edit-item',icon('edit'),'icon-button',`data-id="${i.id}" aria-label="${esc(i.name)} ${B.edit}"`)}</div></div>`).join('')||`<p class="empty compact">${esc(C.packing.empty)}</p>`}</section></div>${input(C.packing.input)}`;}
function applyHiddenCommonState(){const p=place();if(!p)return;const hidden=new Set(p.hiddenCommon||[]);document.querySelectorAll('.item-row[data-id]').forEach(row=>{const is=hidden.has(row.dataset.id)&&row.querySelector('[data-action="hide-common"]');if(!is)return;row.classList.toggle('hidden-common',true);const cb=row.querySelector('input[type="checkbox"]');if(cb)cb.disabled=true;});}
const hiddenObserver=new MutationObserver(()=>applyHiddenCommonState());hiddenObserver.observe(document.querySelector('#app'),{childList:true,subtree:true});
render();applyHiddenCommonState();if(storageError)notify(C.messages.corrupt);else save();
})();
