// Place lists are shown directly; the sidebar retains the separate common editor.
data.categoryTrees=data.categoryTrees||{};
const treeKey=()=>view==='common'?'common':place().id;
const tree=()=>data.categoryTrees[treeKey()]||(data.categoryTrees[treeKey()]=[]);
const parentName=item=>{if(item.category)return item.category;const name=categoryOf(item);return ['기본','공통 준비물'].includes(name)?'기본템':name};
function rememberCategory(parent,child=''){const entries=tree();let entry=entries.find(x=>x.name===parent);if(!entry){entry={name:parent,children:[]};entries.push(entry)}if(child&&!entry.children.includes(child))entry.children.push(child)}
document.querySelector('.category-field label').textContent='준비물 카테고리';
$('newCategory').placeholder='예: 화장품, 의류, 세면도구';
document.querySelector('.category-field p').textContent='준비물 카테고리만 골라도 돼요. 더 나누고 싶으면 하위 카테고리를 입력하세요.';
$('newCategory').insertAdjacentHTML('afterend','<label for="newSubcategory">하위 카테고리 <span class="optional">선택</span></label><input id="newSubcategory" list="subcategorySuggestions" maxlength="50" placeholder="예: 속옷, 양말, 기초 화장품"><datalist id="subcategorySuggestions"></datalist>');
$('editCategoryLabel').textContent='준비물 카테고리';
$('editCategory').insertAdjacentHTML('afterend','<label id="editSubcategoryLabel" for="editSubcategory">하위 카테고리 (선택)</label><input id="editSubcategory" maxlength="50" placeholder="예: 속옷">');
$('items').insertAdjacentHTML('beforebegin','<div id="categoryActions" class="category-actions"><button id="addParentCategory">＋ 준비물 카테고리 추가</button><button id="showItemForm" class="primary">＋ 준비물 추가</button></div>');
$('items').insertAdjacentHTML('afterend','<details id="itemEntry" class="item-entry"><summary>준비물 추가하기</summary><p class="entry-hint">분류를 정하고 아래에 물건 이름을 입력하세요.</p></details>');
$('itemEntry').append(document.querySelector('.category-field'),$('addForm'));
document.body.insertAdjacentHTML('beforeend','<dialog id="categoryDialog"><form id="categoryForm"><h2>카테고리 추가</h2><label for="categoryParent">어디에 만들까요?</label><select id="categoryParent"></select><label for="categoryName">카테고리 이름</label><input id="categoryName" required maxlength="50" placeholder="예: 화장품"><div class="dialog-actions"><button type="button" id="cancelCategory">취소</button><button class="primary">추가</button></div></form></dialog>');
let displayedGroups=[];
function collectGroups(){const groups=new Map();const ensure=name=>{if(!groups.has(name))groups.set(name,{name,children:new Map([['',[]]])});return groups.get(name)};tree().forEach(c=>{const g=ensure(c.name);c.children.forEach(s=>g.children.set(s,[]))});const shown=view==='common'?data.common:[...data.common,...place().items];shown.forEach(item=>{const g=ensure(parentName(item)),sub=item.subcategory||'';if(!g.children.has(sub))g.children.set(sub,[]);g.children.get(sub).push(item)});return [...groups.values()]}
function updateSubSuggestions(){const parent=$('newCategory').value.trim();const g=displayedGroups.find(x=>x.name===parent);$('subcategorySuggestions').innerHTML=g?[...g.children.keys()].filter(Boolean).map(x=>`<option value="${esc(x)}"></option>`).join(''):''}
function showEntry(parent='',sub=''){if(parent)$('newCategory').value=parent;$('newSubcategory').value=sub;$('itemEntry').open=true;updateSubSuggestions();$('itemEntry').scrollIntoView({behavior:'smooth',block:'center'});$('newItem').focus({preventScroll:true})}
function showCategoryDialog(parent=''){const options=displayedGroups.map(g=>g.name);$('categoryParent').innerHTML='<option value="">새 준비물 카테고리</option>'+options.map(n=>`<option value="${esc(n)}">${esc(n)} 안에 하위 카테고리</option>`).join('');$('categoryParent').value=parent;$('categoryName').value='';$('categoryDialog').showModal();$('categoryName').focus()}
const hierarchyRender=render;
render=function(){if(mode==='out'&&view==='essential')view='all';hierarchyRender();const home=mode==='home';$('listFilters').hidden=true;$('addScope').hidden=$('addScopeLabel').hidden=true;$('addScope').value=view==='common'?'common':'essential';$('categoryActions').hidden=$('itemEntry').hidden=home;if(home)return;$('viewHint').textContent=view==='common'?'모든 장소에서 함께 챙기는 물건을 관리하세요.':'기본템부터 세면도구까지, 필요한 물건을 하나씩 챙겨요.';$('listTitle').textContent=view==='common'?'공통 준비물':'필요한 준비물';$('essentialMenu').classList.toggle('selected',view!=='common');displayedGroups=collectGroups();$('categorySuggestions').innerHTML=[...new Set(['기본템','화장품','의류','세면도구',...displayedGroups.map(g=>g.name)])].map(x=>`<option value="${esc(x)}"></option>`).join('');$('items').innerHTML=displayedGroups.map((g,i)=>{const all=[...g.children.values()].flat();return `<section class="category-group"><div class="category-heading"><h3>${esc(g.name)}</h3><span class="category-count">${all.filter(checked).length} / ${all.length}</span></div><div class="group-tools"><button data-new-sub="${i}">＋ 하위 카테고리</button><button data-new-item="${i}">＋ 준비물</button></div>${[...g.children.entries()].map(([sub,items],j)=>`<div class="subgroup">${sub?`<div class="sub-heading"><h4>${esc(sub)}</h4><button data-sub-item="${i}" data-sub-index="${j}" aria-label="${esc(sub)}에 준비물 추가">＋ 추가</button></div>`:''}${items.map(x=>`<div class="item ${checked(x)?'done':''}"><label><input type="checkbox" data-check="${x.id}" ${checked(x)?'checked':''}><span><span class="name">${esc(x.name)}</span>${view!=='common'&&isCommon(x)?'<small>모든 장소 공통</small>':''}</span></label><button data-edit="${x.id}" aria-label="${esc(x.name)} 수정">수정</button></div>`).join('')}${sub&&!items.length?'<p class="empty-sub">아직 준비물이 없어요. 추가 버튼을 눌러 넣어 주세요.</p>':''}</div>`).join('')}${!all.length&&g.children.size===1?'<p class="empty-sub">준비물을 추가하거나 하위 카테고리를 만들어 주세요.</p>':''}</section>`}).join('')||'<div class="empty">준비물 카테고리를 추가해 나만의 준비물을 정리해 보세요.</div>';updateSubSuggestions()};
$('essentialMenu').onclick=()=>{mode='out';view='all';render()};
$('showItemForm').onclick=()=>showEntry();$('addParentCategory').onclick=()=>showCategoryDialog();$('cancelCategory').onclick=()=>$('categoryDialog').close();
$('categoryForm').onsubmit=e=>{e.preventDefault();const name=$('categoryName').value.trim();if(!name)return;const parent=$('categoryParent').value;if(parent)rememberCategory(parent,name);else rememberCategory(name);save();render();$('categoryDialog').close()};
const previousItemClick=$('items').onclick;
$('items').onclick=e=>{const sub=e.target.closest('[data-new-sub]'),add=e.target.closest('[data-new-item]'),nested=e.target.closest('[data-sub-item]');if(sub)return showCategoryDialog(displayedGroups[Number(sub.dataset.newSub)].name);if(add)return showEntry(displayedGroups[Number(add.dataset.newItem)].name);if(nested){const g=displayedGroups[Number(nested.dataset.subItem)];return showEntry(g.name,[...g.children.keys()][Number(nested.dataset.subIndex)])}previousItemClick(e)};
$('newCategory').oninput=updateSubSuggestions;
$('addForm').onsubmit=e=>{e.preventDefault();const name=$('newItem').value.trim();if(!name)return;const category=$('newCategory').value.trim()||'기본템',subcategory=$('newSubcategory').value.trim(),common=view==='common';rememberCategory(category,subcategory);const item={...make([name],common?'공통 필수품':category)[0],category,subcategory};(common?data.common:place().items).push(item);$('newItem').value='';save();render();$('newItem').focus()};
const hierarchyEditor=openEditor;
openEditor=function(type,item){hierarchyEditor(type,item);$('editSubcategoryLabel').hidden=$('editSubcategory').hidden=type!=='item';if(type==='item'){$('editCategory').value=parentName(item);$('editSubcategory').value=item.subcategory||''}};
const hierarchySubmit=$('editForm').onsubmit;
$('editForm').onsubmit=e=>{if(editing.type==='item'&&$('editName').value.trim())editing.item.subcategory=$('editSubcategory').value.trim();hierarchySubmit(e)};
const packingRender=render;
render=function(){packingRender();const shown=mode==='home'?data.locations:view==='common'?data.common:[...data.common,...place().items];$('progressText').textContent=shown.filter(checked).length+' / '+shown.length+(mode==='home'?'개 정리 완료':'개 챙김');};
render();
